[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "py_project_template"
version = "0.0.0"
requires-python = ">=3.8"
dependencies = [
]

[project.optional-dependencies]
dev = []

[project.scripts]
autoux = "py_project_template.app:main"
